env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - XCPROJ="-workspace ReactiveAutomaton.xcworkspace -scheme ReactiveAutomaton"

matrix:
  include:
    - os: osx
      osx_image: xcode8
      language: objective-c
      script:
        - set -o pipefail
        - xcodebuild build-for-testing test-without-building -destination 'platform=OS X' ENABLE_TESTABILITY=YES $XCPROJ | xcpretty
      env:
        - JOB=xcodebuild-macOS

    - os: osx
      osx_image: xcode8
      language: objective-c
      script:
        - set -o pipefail
        - xcodebuild build-for-testing test-without-building -destination 'platform=iOS Simulator,name=iPhone 6s' ENABLE_TESTABILITY=YES $XCPROJ | xcpretty
      env:
        - JOB=xcodebuild-iOS

    - os: osx
      osx_image: xcode8
      language: objective-c
      script:
        - set -o pipefail
        - xcodebuild build-for-testing test-without-building -destination 'platform=tvOS Simulator,name=Apple TV 1080p' ENABLE_TESTABILITY=YES $XCPROJ | xcpretty
      env:
        - JOB=xcodebuild-tvOS

    - os: osx
      osx_image: xcode8
      language: objective-c
      script:
        - set -o pipefail
        - xcodebuild build -destination 'platform=watchOS Simulator,name=Apple Watch - 38mm' $XCPROJ | xcpretty
      env:
        - JOB=xcodebuild-watchOS

    # - os: osx
    #   osx_image: xcode8
    #   script:
    #     - pod lib lint --allow-warnings
    #   env: JOB=pod-lint
